# Generated by Django 4.2.2 on 2023-08-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='name',
            new_name='company_name',
        ),
    ]
