# Generated by Django 4.2.2 on 2023-08-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_rename_name_companyprofile_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_name',
            new_name='name',
        ),
    ]
