# Generated by Django 4.2.2 on 2023-08-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_rename_company_name_companyprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
    ]
