# Generated by Django 4.2.2 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_companyprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(default='Variable', max_length=255),
        ),
    ]
